import { ISpokenLanguage } from "../../../app/model/language.model";

export const spokenLanguages: ISpokenLanguage[] = [
    {name: 'Abkhazian', identifier: "ab"},
    {name: 'Afar', identifier: "aa"},
    {name: 'Afrikaans', identifier: "af"},
    {name: 'Akan', identifier: "ak"},
    {name: 'Albanian', identifier: "sq"},
    {name: 'Amharic', identifier: "am"},
    {name: 'Arabic', identifier: "ar"},
    {name: 'Aragonese', identifier: "an"},
    {name: 'Armenian', identifier: "hy"},
    {name: 'Assamese', identifier: "as"},
    {name: 'Avaric', identifier: "av"},
    {name: 'Avestan', identifier: "ae"},
    {name: 'Aymara', identifier: "ay"},
    {name: 'Azerbaijani', identifier: "az"},
    {name: 'Bambara', identifier: "bm"},
    {name: 'Bashkir', identifier: "ba"},
    {name: 'Basque', identifier: "eu"},
    {name: 'Belarusian', identifier: "be"},
    {name: 'Bengali', identifier: "bn"},
    {name: 'Bihari languages', identifier: "bh"},
    {name: 'Bislama', identifier: "bi"},
    {name: 'Bosnian', identifier: "bs"},
    {name: 'Breton', identifier: "br"},
    {name: 'Bulgarian', identifier: "bg"},
    {name: 'Burmese', identifier: "my"},
    {name: 'Catalan Valencian', identifier: "ca"},
    {name: 'Chamorro', identifier: "ch"},
    {name: 'Chechen', identifier: "ce"},
    {name: 'Chichewa Chewa Nyanja', identifier: "ce"},
    {name: 'Chinese', identifier: "zh"},
    {name: 'Chuvash', identifier: "cv"},
    {name: 'Cornish', identifier: "kw"},
    {name: 'Corsican', identifier: "kw"},
    {name: 'Cree', identifier: "cr"},
    {name: 'Croatian', identifier: "hr"},
    {name: 'Czech', identifier: "cs"},
    {name: 'Danish', identifier: "da"},
    {name: 'Divehi Dhivehi Maldivian', identifier: "dv"},
    {name: 'Dutch Flemish', identifier: "nl"},
    {name: 'Dzongkha', identifier: "dz"},
    {name: 'English', identifier: "en"},
    {name: 'Esperanto', identifier: "eo"},
    {name: 'Estonian', identifier: "et"},
    {name: 'Ewe', identifier: "ee"},
    {name: 'Faroese', identifier: "fo"},
    {name: 'Fijian', identifier: "fj"},
    {name: 'Finnish', identifier: "fi"},
    {name: 'French', identifier: "fr"},
    {name: 'Fulah', identifier: "ff"},
    {name: 'Galician', identifier: "gl"},
    {name: 'Georgian', identifier: "ka"},
    {name: 'German', identifier: "de"},
    {name: 'Greek Modern', identifier: "el"},
    {name: 'Guarani', identifier: "gn"},
    {name: 'Gujarati', identifier: "gu"},
    {name: 'Haitian Haitian Creole', identifier: "ht"},
    {name: 'Hausa', identifier: "ha"},
    {name: 'Hebrew', identifier: "he"},
    {name: 'Herero', identifier: "hz"},
    {name: 'Hindi', identifier: "hi"},
    {name: 'Hiri_Motu', identifier: "ho"},
    {name: 'Hungarian', identifier: "hu"},
    {name: 'Interlingua International Auxil', identifier: "ia"},
    {name: 'Indonesian', identifier: "id"},
    {name: 'Interlingue Occidental', identifier: "ie"},
    {name: 'Irish', identifier: "ga"},
    {name: 'Igbo', identifier: "ig"},
    {name: 'Inupiaq', identifier: "ik"},
    {name: 'Ido', identifier: "io"},
    {name: 'Icelandic', identifier: "is"},
    {name: 'Italian', identifier: "it"},
    {name: 'Inuktitut', identifier: "iu"},
    {name: 'Japanese', identifier: "ja"},
    {name: 'Javanese', identifier: "jv"},
    {name: 'Kalaallisut Greenlandic', identifier: "kl"},
    {name: 'Kannada', identifier: "kn"},
    {name: 'Kanuri', identifier: "kr"},
    {name: 'Kashmiri', identifier: "ks"},
    {name: 'Kazakh', identifier: "kk"},
    {name: 'Central_Khmer', identifier: "km"},
    {name: 'Kikuyu_Gikuyu', identifier: "ki"},
    {name: 'Kinyarwanda', identifier: "rw"},
    {name: 'Kirghiz_Kyrgyz', identifier: "ky"},
    {name: 'Komi', identifier: "kv"},
    {name: 'Kongo', identifier: "kg"},
    {name: 'Korean', identifier: "ko"},
    {name: 'Kurdish', identifier: "ku"},
    {name: 'Kuanyama_Kwanyama', identifier: "kj"},
    {name: 'Latin', identifier: "la"},
    {name: 'Luxembourgish Letzeburgesch', identifier: "lb"},
    {name: 'Ganda', identifier: "lg"},
    {name: 'Limburgan_Limburger_Limburgish', identifier: "li"},
    {name: 'Lingala', identifier: "ln"},
    {name: 'Lao', identifier: "lo"},
    {name: 'Lithuanian', identifier: "lt"},
    {name: 'Luba_Katanga', identifier: "lu"},
    {name: 'Latvian', identifier: "lv"},
    {name: 'Manx', identifier: "gv"},
    {name: 'Macedonian', identifier: "mk"},
    {name: 'Malagasy', identifier: "mg"},
    {name: 'Malay', identifier: "ms"},
    {name: 'Malayalam', identifier: "ml"},
    {name: 'Maltese', identifier: "mt"},
    {name: 'Maori', identifier: "mi"},
    {name: 'Marathi', identifier: "mr"},
    {name: 'Marshallese', identifier: "mh"},
    {name: 'Mongolian', identifier: "mn"},
    {name: 'Nauru', identifier: "na"},
    {name: 'Navajo_Navaho', identifier: "nv"},
    {name: 'North_Ndebele', identifier: "nd"},
    {name: 'Nepali', identifier: "ne"},
    {name: 'Ndonga', identifier: "ng"},
    {name: 'Norwegian Bokmål', identifier: "nb"},
    {name: 'Norwegian Nynorsk', identifier: "nn"},
    {name: 'Norwegian', identifier: "no"},
    {name: 'Sichuan_Yi_Nuosu', identifier: "ii"},
    {name: 'South_Ndebele', identifier: "nr"},
    {name: 'Occitan', identifier: "oc"},
    {name: 'Ojibwa', identifier: "oj"},
    {name: 'Church_Slavic_Old_Slavonic_Chu', identifier: "cu"},
    {name: 'Oromo', identifier: "om"},
    {name: 'Oriya', identifier: "or"},
    {name: 'Ossetian Ossetic', identifier: "os"},
    {name: 'Punjabi Panjabi', identifier: "pa"},
    {name: 'Pali', identifier: "pi"},
    {name: 'Persian', identifier: "fa"},
    {name: 'Polish', identifier: "pl"},
    {name: 'Pashto_Pushto', identifier: "ps"},
    {name: 'Portuguese', identifier: "pt"},
    {name: 'Quechua', identifier: "qu"},
    {name: 'Romansh', identifier: "rm"},
    {name: 'Rundi', identifier: "rn"},
    {name: 'Romanian Moldavian Moldovan', identifier: "ro"},
    {name: 'Russian', identifier: "ru"},
    {name: 'Sanskrit', identifier: "sa"},
    {name: 'Sardinian', identifier: "sc"},
    {name: 'Sindhi', identifier: "sd"},
    {name: 'Northern_Sami', identifier: "se"},
    {name: 'Samoan', identifier: "sm"},
    {name: 'Sango', identifier: "sg"},
    {name: 'Serbian', identifier: "sr"},
    {name: 'Gaelic Scottish Gaelic', identifier: "gd"},
    {name: 'Sinhala_Sinhalese', identifier: "si"},
    {name: 'Slovak', identifier: "sk"},
    {name: 'Slovenian', identifier: "sl"},
    {name: 'Somali', identifier: "so"},
    {name: 'Southern Sotho', identifier: "st"},
    {name: 'Spanish Castilian', identifier: "es"},
    {name: 'Sundanese', identifier: "su"},
    {name: 'Swahili', identifier: "sw"},
    {name: 'Swati', identifier: "ss"},
    {name: 'Swedish', identifier: "sv"},
    {name: 'Tamil', identifier: "ta"},
    {name: 'Telugu', identifier: "te"},
    {name: 'Tajik', identifier: "tg"},
    {name: 'Thai', identifier: "th"},
    {name: 'Tigrinya', identifier: "ti"},
    {name: 'Tibetan', identifier: "bo"},
    {name: 'Turkmen', identifier: "tk"},
    {name: 'Tagalog', identifier: "tl"},
    {name: 'Tswana', identifier: "tn"},
    {name: 'Tonga_Tonga_Islands', identifier: "to"},
    {name: 'Turkish', identifier: "tr"},
    {name: 'Tsonga', identifier: "ts"},
    {name: 'Tatar', identifier: "tt"},
    {name: 'Twi', identifier: "tw"},
    {name: 'Tahitian', identifier: "ty"},
    {name: 'Uighur Uyghur', identifier: "ug"},
    {name: 'Ukrainian', identifier: "uk"},
    {name: 'Urdu', identifier: "ur"},
    {name: 'Uzbek', identifier: "uz"},
    {name: 'Venda', identifier: "ve"},
    {name: 'Vietnamese', identifier: "vi"},
    {name: 'Volapük', identifier: "vo"},
    {name: 'Walloon', identifier: "wa"},
    {name: 'Welsh', identifier: "cy"},
    {name: 'Wolof', identifier: "wo"},
    {name: 'Western Frisian', identifier: "fy"},
    {name: 'Xhosa', identifier: "xh"},
    {name: 'Yiddish', identifier: "yi"},
    {name: 'Yoruba', identifier: "yo"},
    {name: 'Zhuang_Chuang', identifier: "za"},
    {name: 'Zulu', identifier: "zu"}
]